# Generated by Django 2.2.7 on 2019-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2_app', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
