# Generated by Django 2.2.7 on 2019-12-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2_app', '0003_jobs_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='added_by',
            field=models.ManyToManyField(null=True, related_name='jobs_added', to='exam2_app.Users'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='other',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
