# Generated by Django 2.2.7 on 2019-12-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam2_app', '0004_auto_20191213_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='other',
        ),
    ]
